# stages:
#   prepare:
#     cmd: python src/create_features.py
#     deps:
#       - data/adult.data
#       - data/adult.test
#       - src/create_features.py
#     outs:
#       - data/pipeline.pkl
#       - data/processed_train_data.csv
#       - data/processed_test_data.csv

# stages:
#   prepare:
#     cmd: python labs/lab3/create_features.py
#     deps:
#       - data/adult.data
#       - data/adult.test
#       - labs/lab3/create_features.py
#     outs:
#       - data/pipeline.pkl
#       - data/processed_train_data.csv
#       - data/processed_test_data.csv

# stages:
#   prepare:
#     cmd: python labs/lab3/create_features_w_params.py
#     deps:
#       - data/adult.data
#       - data/adult.test
#       - labs/lab3/create_features_w_params.py
#     params:
#       - features.chi2percentile
#       - features.train_path
#       - features.test_path
#     outs:
#       - data/pipeline.pkl
#       - data/processed_train_data.csv
#       - data/processed_test_data.csv

stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
    outs:
      - data/processed_train_features.csv
      - data/processed_test_features.csv
      - data/train_target.csv
      - data/test_target.csv